version: 2.1

jobs:

  vidalog-backend-build:
    docker:
      - image: node:latest
    working_directory: ~/vidalog
    steps:
      - checkout
      - run: ls
      - run: npm i -g @nestjs/cli
      - run: yarn
      - run: ls
      - run: pwd
      - run: yarn run build
      - run: ls
      - persist_to_workspace:
          root: ~/vidalog
          paths:
            - dist
            - node_modules
      - run: echo "BUILD SUCCESS"
  docker-build-and-push:
    docker:
      - image: cimg/node:12.16
    working_directory: ~/vidalog
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          
      - attach_workspace:
          at: ~/vidalog
      - run: |
          docker build -t yongwon0824/vidalog-backend:latest .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
          docker push yongwon0824/vidalog-backend:latest
  deploy:
    machine: true
    steps:
      - checkout
      - run: ssh ec2-user@54.180.166.3 ./vidalog/deploy-backend.sh

workflows:
  version: 2.1
  build:
    jobs:
      - vidalog-backend-build
      - docker-build-and-push:
          requires:
            - vidalog-backend-build
          context:
            - DOCKER
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - docker-build-and-push
          context:
            - AWS
          filters:
            branches:
              only: master